[project]
name = "tabrewind"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "rich>=13.9.4",
    "sqlite-vec>=0.1.6",
]
